server:
  port: 8090
eureka:
  instance:
    ##租期到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 90
    ##租期更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    ##清理间隔
    eviction-interval-timer-in-ms: 10000
    ##关闭自我包含
    enable-self-preservation: false